Update cd.yml
chenge the root directory (ubutus -> white)

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -18,11 +18,11 @@ jobs:
           mkdir -p ~/.ssh
           echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
+          ssh-keyscan -H ip-172-26-15-169 >> ~/.ssh/known_hosts
 
       - name: Deploy to Server
         run: |
-          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_HOST }} << 'EOF'
+          ssh -o StrictHostKeyChecking=no white@ip-172-26-15-169 << 'EOF'
             echo "Deployment starting..."
 
             # Navigate to project directory
@@ -45,8 +45,8 @@ jobs:
             # Start application without requiring sudo
             nohup uvicorn main:app --host 0.0.0.0 --port 5051 --reload > app.log 2>&1 &
 
-            # Restart Nginx without requiring sudo
-            systemctl restart nginx || echo "Failed to restart Nginx"
+            # Restart Nginx
+            sudo systemctl restart nginx || echo "Failed to restart Nginx"
 
             echo "Deployment successful!"
           EOF
