rebase upload the fly io deployment

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -48,7 +48,7 @@ jobs:
       - name: Create Fly.io App (if it doesn't exist)
         run: |
           export PATH="$HOME/.fly/bin:$PATH"
-          flyctl apps create basex --org modibbo-adama-university-yola || echo "App already exists or another error occurred"
+          flyctl apps create basex --owner modibbo-adama-university-yola || echo "App already exists or another error occurred"
 
       - name: Deploy to Fly.io
         run: |
